language: node_js
sudo: false
node_js:
  - "0.10"
before_install:
  - npm update -g npm
before_script:
  - npm install -g grunt-cli

branches:
  only:
    - master
    - develop

notifications:
  email: "ethan@ethanmick.com"

